Updated php action

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -17,4 +17,8 @@ jobs:
         run: composer install --prefer-dist --no-progress --no-suggest
 
       - name: Run authentication scripts
-        run: composer run-script generate-pass
+        run: |
+          composer run-script generate-pass
+          if ! grep -q "$(pwd)" .htaccess; then
+            echo "::error"
+          fi
